package mypackage;

import java.io.FileInputStream;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'malas_000' at '3/23/17 11:49 AM' with Gradle 2.13
 *
 * @author malas_000, @date 3/23/17 11:49 AM
 */

public class Library {
	/*FileInputStream serviceAccount = new FileInputStream("path/to/serviceAccountKey.json");

	FirebaseOptions options = new FirebaseOptions.Builder()
	  .setCredential(FirebaseCredentials.fromCertificate(serviceAccount))
	  .setDatabaseUrl("https://scavengerserver.firebaseio.com/")
	  .build();

	FirebaseApp.initializeApp(options);*/
	
    public boolean someLibraryMethod() {
        return true;
    }
}
